"""create marcel mrc_ tables

Revision ID: af2de81f6bad
Revises: dd92069c8aae
Create Date: 2026-05-06 16:53:07.262266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af2de81f6bad'
down_revision: Union[str, Sequence[str], None] = 'dd92069c8aae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mrc_daily_batches',
    sa.Column('batch_date', sa.Text(), nullable=False),
    sa.Column('leads_picked', sa.Integer(), nullable=True),
    sa.Column('drafts_generated', sa.Integer(), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=True),
    sa.Column('replies_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('batch_date')
    )
    op.create_table('mrc_do_not_contact',
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('added_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('mrc_leads',
    sa.Column('lead_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('salutation', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('company', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('xing', sa.Text(), nullable=True),
    sa.Column('linkedin', sa.Text(), nullable=True),
    sa.Column('industry', sa.Text(), nullable=True),
    sa.Column('sub_industry', sa.Text(), nullable=True),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('dealfront_link', sa.Text(), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('is_owner', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('email_valid', sa.Integer(), nullable=True),
    sa.Column('email_invalid_reason', sa.Text(), nullable=True),
    sa.Column('email_verified_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('lead_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_mrc_leads_city', 'mrc_leads', ['city'], unique=False)
    op.create_index('idx_mrc_leads_industry', 'mrc_leads', ['industry'], unique=False)
    op.create_index('idx_mrc_leads_isowner', 'mrc_leads', ['is_owner'], unique=False)
    op.create_index('idx_mrc_leads_tier', 'mrc_leads', ['tier'], unique=False)
    op.create_table('mrc_deals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Text(), nullable=False),
    sa.Column('stage', sa.Text(), nullable=True),
    sa.Column('value_eur', sa.Float(), nullable=True),
    sa.Column('signed_at', sa.Text(), nullable=True),
    sa.Column('lost_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['mrc_leads.lead_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mrc_emails_sent',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Text(), nullable=False),
    sa.Column('batch_date', sa.Text(), nullable=True),
    sa.Column('touch_number', sa.Integer(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('from_email', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.Text(), nullable=True),
    sa.Column('outlook_entry_id', sa.Text(), nullable=True),
    sa.Column('opened', sa.Integer(), server_default='0', nullable=True),
    sa.Column('bounced', sa.Integer(), server_default='0', nullable=True),
    sa.Column('bounce_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['mrc_leads.lead_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mrc_emails_lead', 'mrc_emails_sent', ['lead_id'], unique=False)
    op.create_table('mrc_lead_status',
    sa.Column('lead_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='New', nullable=True),
    sa.Column('touch_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('last_touch_date', sa.Text(), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('next_action_date', sa.Text(), nullable=True),
    sa.Column('first_sent_at', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.Text(), server_default='Pradip', nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['mrc_leads.lead_id'], ),
    sa.PrimaryKeyConstraint('lead_id')
    )
    op.create_index('idx_mrc_status_current', 'mrc_lead_status', ['status'], unique=False)
    op.create_index('idx_mrc_status_next_date', 'mrc_lead_status', ['next_action_date'], unique=False)
    op.create_table('mrc_meetings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Text(), nullable=False),
    sa.Column('scheduled_at', sa.Text(), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['mrc_leads.lead_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mrc_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['mrc_leads.lead_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mrc_replies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Text(), nullable=False),
    sa.Column('reply_at', sa.Text(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.Text(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('handled', sa.Integer(), server_default='0', nullable=True),
    sa.Column('handled_at', sa.Text(), nullable=True),
    sa.Column('my_response', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['mrc_leads.lead_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mrc_replies_lead', 'mrc_replies', ['lead_id'], unique=False)
    op.create_index('idx_mrc_replies_pending', 'mrc_replies', ['handled'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_mrc_replies_pending', table_name='mrc_replies')
    op.drop_index('idx_mrc_replies_lead', table_name='mrc_replies')
    op.drop_table('mrc_replies')
    op.drop_table('mrc_notes')
    op.drop_table('mrc_meetings')
    op.drop_index('idx_mrc_status_next_date', table_name='mrc_lead_status')
    op.drop_index('idx_mrc_status_current', table_name='mrc_lead_status')
    op.drop_table('mrc_lead_status')
    op.drop_index('idx_mrc_emails_lead', table_name='mrc_emails_sent')
    op.drop_table('mrc_emails_sent')
    op.drop_table('mrc_deals')
    op.drop_index('idx_mrc_leads_tier', table_name='mrc_leads')
    op.drop_index('idx_mrc_leads_isowner', table_name='mrc_leads')
    op.drop_index('idx_mrc_leads_industry', table_name='mrc_leads')
    op.drop_index('idx_mrc_leads_city', table_name='mrc_leads')
    op.drop_table('mrc_leads')
    op.drop_table('mrc_do_not_contact')
    op.drop_table('mrc_daily_batches')
    # ### end Alembic commands ###
