"""create yc grab-source tables

Revision ID: 8da93b8b81bb
Revises: af2de81f6bad
Create Date: 2026-05-06 18:35:26.626936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8da93b8b81bb'
down_revision: Union[str, Sequence[str], None] = 'af2de81f6bad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yc_exported_leads',
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('founder_id', sa.Integer(), nullable=False),
    sa.Column('batch_file', sa.Text(), nullable=True),
    sa.Column('exported_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('lead_id', 'founder_id')
    )
    op.create_table('yc_leads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('company_name', sa.Text(), nullable=False),
    sa.Column('company_domain', sa.Text(), nullable=True),
    sa.Column('company_size', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('signal_type', sa.Text(), nullable=False),
    sa.Column('signal_detail', sa.Text(), nullable=True),
    sa.Column('signal_date', sa.Text(), nullable=True),
    sa.Column('person_name', sa.Text(), nullable=True),
    sa.Column('person_title', sa.Text(), nullable=True),
    sa.Column('person_linkedin', sa.Text(), nullable=True),
    sa.Column('person_email', sa.Text(), nullable=True),
    sa.Column('email_verified', sa.Integer(), server_default='0', nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.Text(), nullable=True),
    sa.Column('last_seen_at', sa.Text(), nullable=True),
    sa.Column('needs_attention', sa.Integer(), server_default='0', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_url', name='uq_yc_leads_source_url')
    )
    op.create_index('idx_yc_leads_attention', 'yc_leads', ['needs_attention'], unique=False)
    op.create_index('idx_yc_leads_domain', 'yc_leads', ['company_domain'], unique=False)
    op.create_index('idx_yc_leads_signal', 'yc_leads', ['signal_type'], unique=False)
    op.create_table('yc_founders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('twitter_url', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('email_status', sa.Text(), nullable=True),
    sa.Column('email_mx', sa.Text(), nullable=True),
    sa.Column('candidates_tried', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('enriched_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['yc_leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id', 'full_name', name='uq_yc_founders_lead_name')
    )
    op.create_index('idx_yc_founders_email_status', 'yc_founders', ['email_status'], unique=False)
    op.create_index('idx_yc_founders_lead', 'yc_founders', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_yc_founders_lead', table_name='yc_founders')
    op.drop_index('idx_yc_founders_email_status', table_name='yc_founders')
    op.drop_table('yc_founders')
    op.drop_index('idx_yc_leads_signal', table_name='yc_leads')
    op.drop_index('idx_yc_leads_domain', table_name='yc_leads')
    op.drop_index('idx_yc_leads_attention', table_name='yc_leads')
    op.drop_table('yc_leads')
    op.drop_table('yc_exported_leads')
    # ### end Alembic commands ###
