"""initial_schema

Revision ID: 024f7748d9a9
Revises: 
Create Date: 2026-05-04 18:32:10.087815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '024f7748d9a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archived_urls',
    sa.Column('post_url', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('post_url')
    )
    op.create_table('autopilot_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fired_at', sa.Text(), nullable=False),
    sa.Column('fired_date', sa.Text(), nullable=False),
    sa.Column('total_queued', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fired_date')
    )
    op.create_table('blocklist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'value', name='uq_blocklist_kind_value')
    )
    op.create_table('company_enrichment',
    sa.Column('company', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('company')
    )
    op.create_table('cvs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cluster', sa.Text(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('stored_path', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('at', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_at', 'events', ['at'], unique=False)
    op.create_table('extension_keys',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('last_used_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('gmail_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('app_password_enc', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('daily_cap', sa.Integer(), server_default='50', nullable=False),
    sa.Column('sent_today', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sent_date', sa.Text(), nullable=True),
    sa.Column('last_sent_at', sa.Text(), nullable=True),
    sa.Column('imap_uid_seen', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('warmup_enabled', sa.Integer(), server_default='1', nullable=False),
    sa.Column('warmup_start_date', sa.Text(), nullable=True),
    sa.Column('connected_at', sa.Text(), nullable=False),
    sa.Column('last_verified_at', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('bounce_count_today', sa.Integer(), server_default='0', nullable=False),
    sa.Column('paused_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_gmail_accounts_status', 'gmail_accounts', ['status'], unique=False)
    op.create_table('kv_settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('leads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_url', sa.Text(), nullable=False),
    sa.Column('posted_by', sa.Text(), nullable=True),
    sa.Column('company', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('tech_stack', sa.Text(), nullable=True),
    sa.Column('rate', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('post_text', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='New', nullable=False),
    sa.Column('gen_subject', sa.Text(), nullable=True),
    sa.Column('gen_body', sa.Text(), nullable=True),
    sa.Column('email_mode', sa.Text(), server_default='company', nullable=False),
    sa.Column('cv_cluster', sa.Text(), nullable=True),
    sa.Column('jaydip_note', sa.Text(), nullable=True),
    sa.Column('skip_reason', sa.Text(), nullable=True),
    sa.Column('skip_source', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.Text(), nullable=False),
    sa.Column('last_seen_at', sa.Text(), nullable=False),
    sa.Column('queued_at', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.Text(), nullable=True),
    sa.Column('replied_at', sa.Text(), nullable=True),
    sa.Column('bounced_at', sa.Text(), nullable=True),
    sa.Column('follow_up_at', sa.Text(), nullable=True),
    sa.Column('needs_attention', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sent_message_id', sa.Text(), nullable=True),
    sa.Column('remind_at', sa.Text(), nullable=True),
    sa.Column('sent_via_account_id', sa.Integer(), nullable=True),
    sa.Column('call_status', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.Text(), nullable=True),
    sa.Column('open_token', sa.Text(), nullable=True),
    sa.Column('open_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('first_opened_at', sa.Text(), nullable=True),
    sa.Column('last_opened_at', sa.Text(), nullable=True),
    sa.Column('scheduled_send_at', sa.Text(), nullable=True),
    sa.Column('ooo_nudge_at', sa.Text(), nullable=True),
    sa.Column('ooo_nudge_sent_at', sa.Text(), nullable=True),
    sa.Column('fit_score', sa.Integer(), nullable=True),
    sa.Column('fit_score_reasons', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_url')
    )
    op.create_index('idx_leads_attention', 'leads', ['needs_attention'], unique=False)
    op.create_index('idx_leads_last_seen', 'leads', ['last_seen_at'], unique=False)
    op.create_index('idx_leads_msgid', 'leads', ['sent_message_id'], unique=False)
    op.create_index('idx_leads_open_token', 'leads', ['open_token'], unique=False)
    op.create_index('idx_leads_remind_at', 'leads', ['remind_at'], unique=False)
    op.create_index('idx_leads_scheduled', 'leads', ['scheduled_send_at'], unique=False, postgresql_where=sa.text('scheduled_send_at IS NOT NULL'))
    op.create_index('idx_leads_status', 'leads', ['status'], unique=False)
    op.create_table('recyclebin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.Column('post_url', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('moved_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_url')
    )
    op.create_table('safety_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_sent_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('daily_sent_date', sa.Text(), nullable=True),
    sa.Column('last_send_at', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('warning_paused_until', sa.Text(), nullable=True),
    sa.Column('autopilot_enabled', sa.Integer(), server_default='0', nullable=False),
    sa.Column('autopilot_hour', sa.Integer(), server_default='10', nullable=False),
    sa.Column('autopilot_minute', sa.Integer(), server_default='0', nullable=False),
    sa.Column('autopilot_count', sa.Integer(), nullable=True),
    sa.Column('autopilot_tz', sa.Text(), server_default='', nullable=False),
    sa.Column('business_hours_only', sa.Integer(), server_default='0', nullable=False),
    sa.Column('safety_mode', sa.Text(), server_default='max', nullable=False),
    sa.Column('warmup_curve_json', sa.Text(), nullable=True),
    sa.Column('followups_autopilot', sa.Integer(), server_default='0', nullable=False),
    sa.Column('followups_hour', sa.Integer(), server_default='11', nullable=False),
    sa.CheckConstraint('id = 1', name='singleton_safety_state'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_opens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.Text(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_opens_lead', 'email_opens', ['lead_id'], unique=False)
    op.create_table('followups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_followups_lead', 'followups', ['lead_id'], unique=False)
    op.create_table('replies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('gmail_msg_id', sa.Text(), nullable=False),
    sa.Column('gmail_thread_id', sa.Text(), nullable=True),
    sa.Column('from_email', sa.Text(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('received_at', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('handled_at', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('auto_draft_body', sa.Text(), nullable=True),
    sa.Column('auto_draft_at', sa.Text(), nullable=True),
    sa.Column('intent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gmail_msg_id')
    )
    op.create_index('idx_replies_lead', 'replies', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_replies_lead', table_name='replies')
    op.drop_table('replies')
    op.drop_index('idx_followups_lead', table_name='followups')
    op.drop_table('followups')
    op.drop_index('idx_email_opens_lead', table_name='email_opens')
    op.drop_table('email_opens')
    op.drop_table('safety_state')
    op.drop_table('recyclebin')
    op.drop_index('idx_leads_status', table_name='leads')
    op.drop_index('idx_leads_scheduled', table_name='leads', postgresql_where=sa.text('scheduled_send_at IS NOT NULL'))
    op.drop_index('idx_leads_remind_at', table_name='leads')
    op.drop_index('idx_leads_open_token', table_name='leads')
    op.drop_index('idx_leads_msgid', table_name='leads')
    op.drop_index('idx_leads_last_seen', table_name='leads')
    op.drop_index('idx_leads_attention', table_name='leads')
    op.drop_table('leads')
    op.drop_table('kv_settings')
    op.drop_index('idx_gmail_accounts_status', table_name='gmail_accounts')
    op.drop_table('gmail_accounts')
    op.drop_table('extension_keys')
    op.drop_index('idx_events_at', table_name='events')
    op.drop_table('events')
    op.drop_table('cvs')
    op.drop_table('company_enrichment')
    op.drop_table('blocklist')
    op.drop_table('autopilot_runs')
    op.drop_table('archived_urls')
    # ### end Alembic commands ###
